# Generated by Django 4.0.1 on 2022-04-06 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 11, 6, 52, 644299, tzinfo=utc)),
        ),
    ]
